# Generated by Django 5.1.3 on 2024-12-10 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='migrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nomi_K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operativka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_turi', models.IntegerField(choices=[(1, 'DDR'), (2, 'DDR2'), (3, 'DDR3'), (4, 'DDR4'), (5, 'DDR5')])),
            ],
        ),
        migrations.CreateModel(
            name='Protsessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_turi', models.IntegerField(choices=[(3, 'Core 3'), (5, 'Core 5'), (7, 'Core 7'), (9, 'Core 9')])),
            ],
        ),
        migrations.CreateModel(
            name='Ram_xotira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_x', models.IntegerField(choices=[(2, '2 GB RAM'), (4, '4 GB RAM'), (8, '8 GB RAM'), (12, '12 GB RAM'), (16, '16 GB RAM'), (24, '24 GB RAM'), (32, '32 GB RAM'), (64, '64 GB RAM'), (128, '128 GB RAM')])),
            ],
        ),
        migrations.CreateModel(
            name='Sanoq_sistema_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.IntegerField(choices=[(2, '2-lik sanoq tizimi (Binary)'), (3, '3-lik sanoq tizimi (Ternary)'), (4, '4-lik sanoq tizimi (Quaternary)'), (5, '5-lik sanoq tizimi (Quinary)'), (6, '6-lik sanoq tizimi (Senary)'), (8, '8-lik sanoq tizimi (Octal)'), (10, '10-lik sanoq tizimi (Decimal)'), (12, '12-lik sanoq tizimi (Duodecimal)'), (16, '16-lik sanoq tizimi (Hexadecimal)')])),
            ],
        ),
        migrations.CreateModel(
            name='Tovarslar_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('izohi', models.CharField(max_length=500)),
                ('narxi', models.IntegerField()),
                ('rasmi', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tur_lar_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_turi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yadro_turi', models.IntegerField(choices=[(2, '2 yadro'), (4, '4 yadro'), (6, '6 yadro'), (8, '8 yadro'), (10, '10 yadro'), (12, '12 yadro'), (16, '16 yadro'), (18, '18 yadro'), (24, '24 yadro'), (32, '32 yadro'), (64, '64 yadro')])),
            ],
        ),
        migrations.CreateModel(
            name='backet_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tovarslar_s')),
            ],
        ),
        migrations.AddField(
            model_name='tovarslar_s',
            name='turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tur_lar_s'),
        ),
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_tobe_linki', models.CharField(max_length=500)),
                ('nomi', models.CharField(max_length=200)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.video_turi')),
            ],
        ),
    ]
