# Generated by Django 5.0.4 on 2024-05-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_nomi_k_operativka_protsessor_ram_xotira_yadro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanoq_sistema_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.IntegerField(choices=[(2, '2-lik sanoq tizimi (Binary)'), (3, '3-lik sanoq tizimi (Ternary)'), (4, '4-lik sanoq tizimi (Quaternary)'), (5, '5-lik sanoq tizimi (Quinary)'), (6, '6-lik sanoq tizimi (Senary)'), (8, '8-lik sanoq tizimi (Octal)'), (10, '10-lik sanoq tizimi (Decimal)'), (12, '12-lik sanoq tizimi (Duodecimal)'), (16, '16-lik sanoq tizimi (Hexadecimal)')])),
            ],
        ),
    ]
